apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      initContainers:
      - name: migration
        image: notification-migration:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: notification-api-config
      containers:
      - name: notification-api
        image: notification-api:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: notification-api-config
        ports:
        - containerPort: 8080