apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  namespace: task-system
  labels:
    app: task-api
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: api-foundation:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000