apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-worker-deployment
  #namespace: task-system
  labels:
    app: task-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-worker-pod
  template:
    metadata:
      labels:
        app: task-worker-pod
    spec:

      volumes:
      - name: shared-logs
        emptyDir: {}

      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        env:
        - name: TASK_API_URL
          value: "http://task-api-service:80"

        # 2. Mount the volume for the worker to write to
        volumeMounts:
        - name: shared-logs
          mountPath: /app/logs

      - name: sidecar
        image:  sidecar:latest
        imagePullPolicy: Never

        # 3. Mount the same volume for the sidecar to read from
        volumeMounts:
        - name: shared-logs
          mountPath: /app/logs
          readOnly: true
        

