apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      volumes:
      - name: ephemeral-storage
        emptyDir: {}
      containers:
      - name: notification-worker
        image: notification-worker:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: notification-worker-config
        volumeMounts:
        - name: ephemeral-storage
          mountPath: /app/logs
      - name: notification-sidecar
        image: notification-sidecar:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: notification-worker-config
        volumeMounts:
        - name: ephemeral-storage
          mountPath: /app/logs