apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
      - name: notification-worker
        image: notification-worker:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: notification-worker-config