FROM golang:1.25.1-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY main.go task.txt ./

RUN go build -o app main.go

#---------- stage-2 ------------------

FROM alpine:latest

WORKDIR /root
COPY --from=builder /app/app .
EXPOSE 8080

CMD [ "./app" ]