apiVersion: v1
kind: Service
metadata:
  name: postgres-11
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # optional (for stateful connection)
